# Generated by Django 4.2.3 on 2023-08-03 21:02

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('description_short', models.TextField(null=True, verbose_name='Краткое описание')),
                ('description_long', tinymce.models.HTMLField(null=True, verbose_name='Полное описание')),
                ('lat', models.DecimalField(decimal_places=16, max_digits=20, verbose_name='Широта')),
                ('long', models.DecimalField(decimal_places=16, max_digits=20, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Картинка')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='places.place', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
                'ordering': ['order_num'],
            },
        ),
    ]
