# Generated by Django 4.2.3 on 2023-08-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description_short', models.TextField(null=True)),
                ('description_long', models.TextField(null=True)),
                ('lat', models.DecimalField(decimal_places=16, max_digits=20)),
                ('long', models.DecimalField(decimal_places=16, max_digits=20)),
            ],
        ),
    ]
