# Generated by Django 4.2.3 on 2023-08-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_picture_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['order_num'], 'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.RemoveField(
            model_name='place',
            name='order_num',
        ),
        migrations.AddField(
            model_name='picture',
            name='order_num',
            field=models.IntegerField(default=1),
        ),
    ]
