# Generated by Django 4.2.3 on 2023-08-02 19:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_options_alter_picture_order_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(null=True, verbose_name='Полное описание'),
        ),
    ]
